INSERT INTO category (name, description)
VALUES
('Baby', 'Everything for your little one'),
('Beauty', 'Makeup, skincare, hair care, and more'),
('Books', 'Hardcover, paperback, audiobooks, and e-readers'),
('Cars', 'New and used cars, car parts, and accessories'),
('Clothing', 'Men''s, women''s, and children''s clothing'),
('Computers', 'Laptops, desktops, tablets, and accessories'),
('Consumer Electronics', 'TVs, stereos, headphones, and more'),
('Crafts', 'Supplies and tools for all your crafting needs'),
('Electronics', 'Cell phones, computers, tablets, and more'),
('Food', 'Groceries, produce, and gourmet items'),
('Furniture', 'Bedroom, living room, dining room, and more'),
('Garden', 'Plants, flowers, tools, and supplies'),
('Gifts', 'For every occasion'),
('Grocery', 'Food, beverages, and household items'),
('Health', 'Vitamins, supplements, and natural remedies'),
('Home Decor', 'Pillows, rugs, curtains, and more'),
('Home Improvement', 'Tools, hardware, and paint'),
('Jewelry', 'Fine jewelry, fashion jewelry, and watches'),
('Kids', 'Toys, games, clothes, and more'),
('Kitchen', 'Cookware, bakeware, utensils, and appliances'),
('Lawn and Garden', 'Power tools, hand tools, mowers, and more'),
('Mens', 'Men''s clothing, shoes, and accessories'),
('Movies & TV', 'DVDs, Blu-rays, and streaming services'),
('Music & CDs', 'CDs, vinyl, and digital downloads'),
('Office Supplies', 'Paper, pens, printers, and more'),
('Outdoors', 'Camping, hiking, fishing, and more'),
('Pets', 'Food, supplies, and toys for your furry friend'),
('Pharmacy', 'Prescription drugs, over-the-counter medications, and health and beauty aids'),
('Shoes', 'Men''s, women''s, and children''s shoes'),
('Sports', 'Fan gear, equipment, and apparel'),
('Toys', 'Toys for all ages'),
('Travel', 'Luggage, travel guides, and maps'),
('Womens', 'Women''s clothing, shoes, and accessories'),
('Baby Gear', 'Strollers, car seats, cribs, and more'),
('Bath & Body', 'Soap, shampoo, lotion, and more'),
('Gift Cards', 'For any occasion'),
('Housewares', 'Kitchen gadgets, cleaning supplies, and more'),
('Luggage', 'Suitcases, backpacks, and duffel bags'),
('Patio Furniture', 'Chairs, tables, umbrellas, and more'),
('Pet Supplies', 'Food, toys, and treats for your furry friend'),
('Video Games', 'Consoles, games, and accessories'),
('Watches', 'Men''s, women''s, and children''s watches');